### ISSUE TITLE
Ausgabe der Ergebnisse der 3 Sensoren auf dem kleinen Display

### ISSUE THREAD

**Issue by janalo** [EmbeddedDuo/AutoGewaechshaeuschen#2]

**Comment by zZeRIoN** [comment]
15.01: LCD Task recieved erfolgreich die Temperaturwerte der Pins wird aber noch nicht angezeigt.

**Comment by zZeRIoN** [comment]
Durchschnittstemperatur und Durchschnittshumidity werden auf dem LCD angezeigt
